Admin settings
pondersource/oc-sciencemesh pull request #46
Opened 2023-02-07 17:48 UTC by parhamin2010

2023-02-08 10:53 UTC, navid-shokri requested changes

2023-02-08 10:53 UTC, navid-shokri commented on lib/Controller/SettingsController.php
> +				    			IConfig $sciencemeshConfig,
care about indentations.

2023-02-08 11:13 UTC, parhamin2010 commented on lib/Controller/SettingsController.php
> +				    			IConfig $sciencemeshConfig,
fixed

2023-02-08 12:08 UTC, parhamin2010 commented
@navid-dada if you confirm, please merge this PR with main.

2023-02-10 07:33 UTC, navid-shokri approved these changes

2023-02-10 07:33 UTC, navid-shokri approved these changes

2023-02-10 08:52 UTC, merged